apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUServiceTemplate
metadata:
  name: ovn
  namespace: dpf-operator-system
spec:
  deploymentServiceName: "ovn"
  helmChart:
    source:
      repoURL: <OVN_TEMPLATE_CHART_URL>
      chart: ovn-kubernetes-chart
      version: <OVN_CHART_VERSION>
    values:
      global:
        enableEgressIP: "true"
        egressIpHealthCheckPort: "0"
        enableEgressFirewall: "true"
        enableEgressQoS: "true"
        enableEgressService: "true"
        enableMultiNetwork: "false"
        enableMultiNetworkPolicy: "true"
        enableAdminNetworkPolicy: "true"
        enableNetworkSegmentation: "true"
      commonManifests:
        enabled: true
      dpuManifests:
        image:
          repository: <OVN_KUBERNETES_IMAGE_REPO>
          tag: <OVN_KUBERNETES_IMAGE_TAG>
        <OVN_KUBERNETES_UTILS_IMAGES>
        enabled: true
        ovnMultiNetworkEnable: "true"
        cniBinDir: /var/lib/cni/bin/
        cniConfDir: /run/multus/cni/net.d
      <OVN_DAEMONSET_VERSION>
      leaseNamespace: "openshift-ovn-kubernetes"
      gatewayOpts: "--gateway-interface=br-dpu"
